home/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.show_home, name='home'),
]

product/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('book', views.show_book, name='book'),
    path('book_detail/<book_id>', views.book_detail, name='book_detail'),
]

traverse_book/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('product/', include('product.urls')),
    path('order/', include('order.urls')),
    path('customer/', include('customer.urls')),
    path('checkout/', include('checkout.urls')),
    

] 

product/models.py
from django.db import models
from cloudinary.models import CloudinaryField
from isbn_field import ISBNField
# Create your models here.

class Language(models.Model):
    """model to store language option for books"""
    LANGUAGE_CHOICE = (
        (1, 'English'),
        (2, 'French'),
        (3, 'German'),
        (4, 'Japanese'),
        (5, 'Chinese'),
        (6, 'Russian'),
        (7, 'Greek'),
    )    
    language = models.IntegerField(choices=LANGUAGE_CHOICE, default=1)
    note = models.CharField(max_length=1000, null=True, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

class Category(models.Model):
    """model to store cateogy of books"""
    GENRE_CHOICE = (
        (1, 'Romance fiction'),
        (2, 'Thriller fiction'),
        (3, 'Detective fiction'),
        (4, 'Classic'),
        (5, 'Nonfiction'),
        (6, 'Sci-fi/Fantasy'),
        (7, 'Poetry'),
        (8, 'Science'),
        (9, 'Social Science'),
        (10, 'Philosophy'),
        (11, 'Gender'),
        (12, 'Translated Fiction'),
        (13, 'Literary Fiction'),
    )

    REGION_CHOICE = (
        (1, 'United States'),
        (2, 'United Kingdom'),
        (3, 'Germany'),
        (4, 'France'),
        (5, 'Japan'),
        (6, 'Russia'),
        (7, 'Greece'),
        (8, 'China'),
    ) 

    genre = models.IntegerField(choices=GENRE_CHOICE, default=1)
    region = models.IntegerField(choices=REGION_CHOICE, default=1)
    
    

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)


class Product(models.Model):
    """model to store book products"""
    COVER_CHOICE = (
        (1, 'Hardback'),
        (2, 'Paperback'),
        (3, 'Softcover'),
    )
    YEAR_CHOICE = zip(range(1000, 2023), range(1000, 2023))
    name = models.CharField(max_length=200, null=True, blank=True)
    publisher = models.CharField(max_length=100, null=True, blank=True)
    author = models.CharField(max_length=100, null=True, blank=True)
    year_of_publication = models.IntegerField(choices= YEAR_CHOICE, default = 1)
    number_of_pages = models.IntegerField(null=True, blank=True)
    isbn = ISBNField()
    cover = models.IntegerField(choices= COVER_CHOICE, default=1)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, null=True, blank = True)
    language = models.ForeignKey(
        Language, on_delete=models.CASCADE, null=True, blank = True)
    price = models.DecimalField(
        max_digits=10, decimal_places=2, null=False, default=0.00)

    def __str__(self):

        return self.name    



class ProductImage(models.Model):
    """model to store product image"""
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = CloudinaryField(
        'product_image', folder='product_images', null=True, blank=True
    )
    alt_text = models.CharField(max_length=1000, null=True, blank=True)
    image_url = models.URLField(max_length=1024, null=True, blank=True)
    default_image = models.BooleanField(
        default=False,
    )

    def __str__(self):
        return self.product.name

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        if self.default_image:
            for image in self.product.images.all().exclude(id=self.id):
                image.default_image = False
                image.save()

    @property
    def image_url(self):
        if self.image:
            return self.image.url
        return 'static/images/default_product_image.png'

product/views.py
from django.shortcuts import render, redirect, reverse
from .models import Product, ProductImage, Language, Category 
from django.shortcuts import get_object_or_404
from django.contrib import messages
from django.db.models import Q
# Create your views here.

def show_book(request):

    books = Product.objects.all()
    categories = Category.objects.all()
    query = None
    language = Language.objects.all()
    images = ProductImage.objects.all()
    sort = None
    direction = None
    
    if request.GET:   
        if 'sort' in request.GET:
            sortkey = request.GET['sort']
            sort = sortkey
            
            if 'direction' in request.GET:
                direction = request.GET['direction']
                if direction == 'desc':
                    sortkey = f'-{sortkey}'
            books = books.order_by(sortkey)
        if 'q' in request.GET:
            query = request.GET['q']
            if not query:
                messages.error(request, "Please enter searching keyword")
                return redirect(reverse('book'))

            queries = Q(name__icontains=query) | Q(author__icontains=query)| Q(isbn__icontains=query)| Q(publisher__icontains=query)
            books = books.filter(queries)
            current_sort = f'{sort}_{direction}'


    context = {
        'books': books,
        'images': images,
        'current_sort': sort,
        'search': query,
        
    }
    return render(request, 'book/book.html', context)

def book_detail(request, book_id):

    books = get_object_or_404(Product, id=book_id)
    images = ProductImage.objects.all()
    categories = Category.objects.all()
    language = Language.objects.all()
    context = {
        'books': books,
        'images': images,
        'categories': categories,
        'language': language,
    }

    return render (request, 'book/book_detail.html', context)

product/templates/book/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <form method="GET" action="{% url 'book' %}">
                <div>
                    <input class="form-control" type="text" name="q"
                        placeholder="Search book name, author's name, publisher or ISBN">
                    <button class="form-control bg-dark text-white" type="submit">
                        <h6 class="title-text text-white">
                            Search
                            <i class="fa-solid fa-magnifying-glass text-white">

                            </i>
                        </h6>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="container">
        <div class="row">
            
                <button class="btn btn-dark dropdown-toggle col-lg-12 col-lg-3
            mt-4" 
                type="button" data-toggle="dropdown">
                    <h5 class="title-text text-white">Sort by</h5>
                </button>
                <ul class="dropdown-menu">
                    <li>

                        <a href="{% url 'book' %}">
                            <h5 class="title-text text-dark">

                                None
                            </h5>
                        </a>
                    </li>
                    <li>

                        <a href="{% url 'book' %}?sort=price&direction=asc">
                            <h5 class="title-text text-dark">
                            Price (low to high)
                            </h5>
                        </a>

                    </li>
                    <li>

                        <a href="{% url 'book' %}?sort=price&direction=desc">
                            <h5 class="title-text text-dark">
                            Price (high to
                            low)
                            </h5>
                        </a>
                    </li>
                    <li>

                        <a href="{% url 'book' %}?sort=name&direction=asc">
                            <h5 class="title-text text-dark">
                            Name (A-Z)
                            </h5>
                        </a>
                    </li>
                    <li>

                        <a href="{% url 'book' %}?sort=name&direction=desc">
                            <h5 class="title-text text-dark">
                            Name (Z-A)
                            </h5>
                        </a>
                    </li>
                </ul>

            




        </div>

    </div>

    {% if not books %}
    <div class="books-container col-lg-12 col-lg-4">
        <div class="row mt-5 mb-7">
            <div class="col-lg-12 col-lg-3 mb-5 display=block">
                <h1 class="title-text">Sorry, no result found. Please search again.</h1>
            </div>
            <div class="col-lg-12 col-lg-3 display=block">
                <a href="{% url 'book' %}">
                    <button class="col-lg-4 bg-dark text-white">
                        <p>
                            Go back

                        </p>
                    </button>
                </a>
            </div>
        </div>
    </div>

    {% endif %}

    {% if books %}
    <div class="row mt-5 mb-4">
        <div class="books-container ">

            <div class="row">

                {% for book in books %}
                <div class="col-sm-5, col-md-4, col-xl-3, col-lg-3
                    {% if books|length == 1 %} col-lg-12 {% endif %}">
                    <div class="card h-200 border-0">

                        {% for image in images %}
                        {% if image.product.name == book.name %}
                        <a href="{% url 'book_detail' book.id %}">
                            <div class="card h-5 w-5 border-0">

                                <img class="card-img" src="{{image.image_url}}">
                            </div>
                        </a>
                        {% endif %}
                        {% endfor %}
                        <div class="card-body">
                            <h5 class="md-0 title-text">
                                <strong>

                                    {{book.name}}
                                </strong>
                            </h5>

                        </div>
                        <div class="card-body">
                            <p class="title-text">Author: {{book.author}}</p>
                        </div>
                        <div class="card-body">
                            <p class="title-text">Publisher: {{book.publisher}}</p>
                        </div>
                        <div class="card-body">
                            <p class="title-text">
                                Year of Publication: {{book.year_of_publication}}
                            </p>
                        </div>

                        <div class="card-body font-weight-bold">
                            <p class="title-text">
                                <strong>

                                    Price: ${{book.price}}
                                </strong>
                            </p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            {% endif %}
        </div>
    </div>

</div>

</div>


{% endblock %}

product/templates/book/book_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container mt-4">
    <div class="row">
        <div class="col">
            <form method="GET" action="{% url 'book' %}">
                <div>
                    <input class="form-control" type="text" name="q"
                        placeholder="Search book name, author's name, publisher or ISBN">
                    <button class="form-control bg-dark text-white" type="submit">
                        <p>
                            Search
                            <i class="fa-solid fa-magnifying-glass text-white">
                                
                            </i>
                        </p>
                    </button>
                </div>
            </form>
        </div>
    </div>

    <div class="row mt-5 mb-4">
        <div class="books-container">
            <div class="row ml-5">
                {% if books %}
                <div class="col-sm-5, col-md-4, col-xl-3, col-lg-6 justify-content-center">
                    <div class="card h-200 border-0">
                        {% for image in images %}
                        {% if image.product.name == books.name %}
                        <div class="card h-5 w-5 border-0">

                            <img src="{{image.image_url}}">
                        </div>
                        {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-sm-5, col-md-4, col-xl-3, col-lg-5 justify-content-center">
                    <div class="card-body">
                        <h5 class="md-0">{{books.name}}</h5>
                        


                        <p>Author: {{books.author}}</p>
                        <p>Publisher: {{books.publisher}}</p>
                        <p>
                            Year of Publication: {{books.year_of_publication}}
                        </p>
                        <p>Page: {{books.number_of_pages}} pages</p>
                        <p class="font-weight-bold">
                            Price: ${{books.price}}
                        </p>
                        {% if books.category %}

                        <p class="md-0">
                            Genre: {{books.category.get_genre_display}}
                        </p>
                        {% endif %}
                        {% if books.language %}
                        <p class="md-0">
                            Language: {{books.language.get_language_display}}
                        </p>
                        {% endif %}
                        <p class="md-0">ISBN: {{books.isbn}} </p>
                        <p class="md-0">
                            Cover: {{books.get_cover_display}}
                        </p>
                    </div>
                </div>
            </div>
            <div class="col-lg-12 mt-3 ml-2 mb-4">
                <div class="row">
                    <div class="col">
                        <form>
                            <div class="dropdown-content">
                                
                            </div>
                            
                        </form>
                    </div>
                </div>
                <a href="{% url 'book' %}">
                    <button class=" col-lg-12 col-lg-4 bg-dark text-white">
                        <p>
                            Continue shoping
                        </p>
                    </button>
                </a>
                
                <form action="{% url 'add_order' books.id %}" method="POST"
                    class="mt-3" name="item">
                    {% csrf_token %}
                    <input class="form-control" type="number"
                        name="quantity" value="1" min="1" max="5"
                        data-item_id="{{ books.id }}"
                        id="id_qty_{{ books.id }}">
                    <button class=" col-lg-12 col-lg-4 bg-success text-white" 
                        type="submit" name="item">
                        <p>
                            Add to cart
                            <i class="fa-solid fa-cart-shopping text-white"></i>
                        </p>
                        
                    </button>
                </form>
                
                
            </div>
            {% endif %}
        </div>
    </div>
</div>


{% endblock %}